# Generated by Django 3.2.20 on 2023-09-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('brand', models.CharField(max_length=80)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=90)),
                ('vendor', models.CharField(max_length=80)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Product_Master',
            },
        ),
    ]
