# Generated by Django 3.2.20 on 2023-09-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('address', models.TextField(max_length=200)),
                ('contact', models.BigIntegerField()),
            ],
            options={
                'db_table': 'CUSTOMER_MASTER',
            },
        ),
    ]
